import Head from 'next/head'
import { useRouter } from 'next/router'
import { fetchUser, fetchUserById } from '../../helpers/api-util';

export default function User(props) {
    const router=useRouter();
    console.log(router.pathname,router.query.user)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by creat e next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{props.userData.name}</h1>
    </>
      
  )
}
export async function getServerSideProps(context){
    const {params}=context;
    const userData=await fetchUserById(params.user);
    return {
        props:{
            userData
        }
    } 
}
// export async function getStaticProps(context){
//     console.log(context.params.user)
    // const userData=await fetchUserById(context.params.user);
//     return {
//       props:{
//         userData:userData
//       }
//     }
//   }
//   export async function getStaticPaths(){
//       const users=await fetchUser()
//       const paths=users.map(u=>({params:{user:`${u.id}`}}))
//       return {
//           paths:paths,
//           fallback:false
//       }
//   }