import Head from 'next/head'

import Link from 'next/link'
import { fetchUser } from '../../helpers/api-util'


export default function Users(props) {
    const user=[
        {name:'Mani'},
        {name:"mani1"}
    ]
  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>List of User</h1>
      <ul>
      {props.userData.map(u=>(

          <li key={u.name}><Link href={{pathname:'/users/[user]',query:{user:u.id}}}>{u.name}</Link></li>
      ))}
      </ul>
      
    </>
      
  )
}

export async function getStaticProps(){
    const userData=await fetchUser();
    return {
      props:{
        userData
      }
    }
  }