import Head from 'next/head'
import { useSelector,useDispatch } from 'react-redux'
import { incrementCounter,decrementCounter } from '../redux/actions/action'


export default function Home() {
  let value=useSelector((state)=>state.counter.value)
  const dispatch=useDispatch()
  const handleDecremnt=()=>{
    dispatch(decrementCounter())
  }
  const handleIncremnt=()=>{
    dispatch(incrementCounter())
  }


  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home Page</h1>
      <div>
        <p>value {value}</p>
        <button onClick={handleIncremnt}>Increment</button>
        <button onClick={handleDecremnt}>Decrement</button>
      </div>
    </>
      
  )
}
